### PR TITLE
Style

### PR DESCRIPTION
**Pull request by carriewright11**
#### What changes are being implemented in this Pull Request?
1)adding favicon (assets/ITN_favicon.png and index.Rmd)
2)updating style colors (big-image-itcr.html) 
3) added new main image (big-image-itcr.html)
4) adding different button to toc (which includes arrow image) (_output.yml)
5) moving references from about to its own section at end (references.rmd and _bookdown.yml)
6) modifications for section titles(_bookdown.yml)
7) added title slide (01-intro.Rmd)
8) added more credits (About.Rmd)
9) modified index file to include slide info

#### What was your approach?
Made the course more like mine in a style way. Will update anything missing to the template.

Still confused about why the title is "about". This seems very important to fix as well :/

#### What GitHub issue does your pull request address?

#67 
Making our courses more consistent

### New Content Checklist

- [ ] New content/chapter is in an Rmd file with [this kind of format and headers](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/02-chapter_of_course.Rmd).

- [ ] New content/chapter contains [Learning Objectives and are in the correct format](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#learning-objectives-formatting).

- [ ] [Bookdown successfully re-renders and any new content files have been added to the _bookdown.yml](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#bookdown-rendering).

- [ ] Spell check runs successfully (either using [Github actions style-n-check](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#spell-check) or [running manually](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#running-spell-check-and-styler-manually)).

- [ ] Any newly necessary packages that are needed have been added to the [Dockerfile and image](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#adding-packages-to-the-dockerfile).

- [ ] Images are in the [correct format for rendering](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#adding-images-and-graphics-in-text).

- [ ] Every new image has [alt text and is in a Google Slide](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/getting_started.md#adding-images-and-graphics-in-text).

- [ ] Each slide is described in the notes of the slide so learners relying on a screen reader can access the content. See https://lastcallmedia.com/blog/accessible-comics for more guidance on this.

- [ ] The color palette choices of the slide are contrasted in a way that is friendly to those with color vision deficiencies.
You can check this using [Color Oracle](https://colororacle.org/).

### CODE REVIEW

**Comment by carriewright11** [comment]
Everything looks pretty similar to mine now. The only issue is the title is "about". Still trying to figure out why, but kinda confused.

**Comment by carriewright11** [comment]
I will update the template about style as well. Want to also make it more consistent between naming things with ITN or ITCR.

**Comment by carriewright11** [comment]
OK the only major thing I see left for bookdown - is that the images are left aligned and smaller. I made the title image like mine which was with out.width = "100%", would ideally like to add to all images maybe? When I look at the current rendered version they look bigger https://jhudatascience.org/ITCR_Documentation_and_Usability/index.html then when I preview it... maybe that was from when the slides were extra big

**Comment by carriewright11** [comment]
Title is now fixed

**Comment by cansavvy** [comment]
Thanks for doing this styling stuff!! Only one question. There's these weird squares (You can click on the preview to see for yourself): 

Screen Shot 2021-09-27 at 8 33 50 PM

**Comment by carriewright11** [comment]
When I try to render it myself I see the arrows. Perhaps we have another version difference, but it is strange because the current hosted version  has the arrows, as well as the bookdown template.

**Comment by cansavvy** [comment]
Hmm... Odd. It could be a weird htmlpreview quirk. We can merge and see if it's still there.

**Review by cansavvy — APPROVED** [review]
This looks great! Thanks for doing this!

**Pull request merged**
